### ISSUE TITLE
关于动态监控的曲线图的数据格式想问一下是什么样的

### ISSUE THREAD

**Issue by zdui** [ashtonmeuser/vue-cloudwatch-dashboard#3]
大神帮忙，我下载来的代码曲线图的接口调不到，我想知道这块的json格式是怎么样的，是后台实时的只传一个数据的么

**Comment by zdui** [comment]
大神，你那个X轴当前动态时间是咋搞得，我启动项目后看不到你的效果图，请赐教，多谢指点，期待您的回复 @ashtonmeuser

**Comment by ashtonmeuser** [comment]
Please thoroughly read through the README. Because I don't know what metrics you have available from AWS, this repo requires some customization. 
First, you must create a `metrics.json` file in the `src` directory. Configure this file to access the appropriate CloudWatch metrics. The dimension name and value as well as the metric name and value can be found from the CloudWatch Metrics page within AWS.
The `App.vue` file will need to be customized to reflect the metrics defined in the `metric.json` file. You can access specific metrics using the `DatasetArray.ided()` method.
